apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: python-processor
            image: python:3.7
            command: ["python", "/rabbitmq-util/rmq_purge_all_queues.py"]
          restartPolicy: OnFailure